
= Minetest Mods learntocount 

This mod provide equation to resolve. 
Its purpose is to help learn the addition, subtraction, multiplication and division tables.

Generated map contains some block number to compose results. 
It's also add some equation (like '3+5='). 
Equation could not be destroyed but they can be resolver adding right blocks after the equal.
When the result is correct, there is a reward. 
a new equation can be proposed or else it disappears.

== Installation

To install this mod link:../../archive/main.zip[download it], and extract the zip to <your minetest folder>/mods/learntocount.

On Linux, the folder which contains the mods folder is .minetest in your home directory. (You may need to use ctrl+h to show hidden files.)

On Windows, the mods folder will be located around the directory where minetest.exe is located, and can be accessed from the main directory where the minetest's data is located.

If you need more assistance with this, please refer to link:https://wiki.minetest.net/Installing_Mods[these instructions]

== Nodes

* 'Digit blocks': A-Z 0-9 and operators
* 'Map generator'

== Tests


To run tests you can install link:https://rubenwardy.com/minetest_modding_book/en/quality/unit_testing.html[install busted and run tests].

You can use this link:https://github.com/imega-docker/busted[docker image] to run tests with following commands:
----
cd [minetest directory]
docker run -v $(pwd):/minetest -w /minetest/mods/learntocount imega/busted .
----